### ISSUE TITLE
[Suggestion] Odd(uneven) village well

### ISSUE THREAD

**Issue by drakray** [TheExceptionist/Coherent-Villages#1]
If possible, I think a 3x3(5x5 w/ cobble) Well would be nice, since the Paths are 3 wide.
Always bothered me to have a non-centered Well.

Maybe even a nicer Well, one that ~~Stupidificate~~ Villager can get out of.

**Comment by TheExceptionist** [comment]
Alright, that shouldn't be to bad to do.
Thanks for your input!

**Comment by TheExceptionist** [comment]
Actually this will be a lot more difficult than I though. So I'll save it for later

**Comment by TheExceptionist** [comment]
Done
