### ISSUE TITLE
NPE spam in server log

### ISSUE THREAD

**Issue by V10lator** [TheExceptionist/Coherent-Villages#11]
This is on a server with beta 1: https://pastebin.com/78fu9kCD

**Comment by V10lator** [comment]
As a side node (I don't want to open a new report for it as it's not really a bug) your Soldier seems to need some optimisation:

![image](https://user-images.githubusercontent.com/1312422/45926584-ac956580-bf24-11e8-9480-2fc1749c8844.png)
(Screenshot taken from JProfiler)

**Comment by TheExceptionist** [comment]
Also I'll look into fixing that bug

**Comment by TheExceptionist** [comment]
Tell me if it's fixed in the next version

**Comment by V10lator** [comment]
Looks good. :)
For the performance: Now the server shows "Can't keep up! Did the system time change, or is the server overloaded?" near villages. Anyway, take your time and keep on rocking!
