### ISSUE TITLE
Villages in water (maybe BoP related)

### ISSUE THREAD

**Issue by V10lator** [TheExceptionist/Coherent-Villages#12]
![image](https://user-images.githubusercontent.com/1312422/45928663-b11f4580-bf47-11e8-92eb-c8d1de0d30ee.png)
This seems to be in Deep Ocean biomes from Biomes O' Plenty.

**Comment by TheExceptionist** [comment]
No, that's a feature.
You can disable it in the config file

**Comment by TheExceptionist** [comment]
D

**Comment by V10lator** [comment]
Whoops, my fault. Sorry about that.
