### ISSUE TITLE
Suggestion: Ingame Config

### ISSUE THREAD

**Issue by dave75vgnut** [TheExceptionist/Coherent-Villages#16]
Can you make the config accessible ingame. I only ask because I've had problems w/ it crashing after changing it when starting minecraft. Here is Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  HCASM (HammerCore-1.12.2-2.0.2.3.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  MuonPlugin (muon-0.2-1.12.jar)
  BaseMetals (BaseMetals-1.12-2.5.0-beta6.280.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 9/27/18 9:23 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Coherent Villages Mod Beta (coherentvillages)
Caused by: java.lang.NumberFormatException: For input string: "0Ice Plains"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at net.theexceptionist.coherentvillages.main.Main.readConfig(Main.java:292)
	at net.theexceptionist.coherentvillages.main.Main.preInit(Main.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 215022800 bytes (205 MB) / 671580160 bytes (640 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 Optifine OptiFine_1.12.2_HD_U_D1 92 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                    | Version                  | Source                                               | Signature                                |
	|:----- |:------------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                             | 1.12.2                   | minecraft.jar                                        | None                                     |
	| UCH   | mcp                                   | 9.42                     | minecraft.jar                                        | None                                     |
	| UCH   | FML                                   | 8.0.99.99                | forge-1.12.2-14.23.4.2759.jar                        | None                                     |
	| UCH   | forge                                 | 14.23.4.2759             | forge-1.12.2-14.23.4.2759.jar                        | None                                     |
	| UCH   | muon                                  | 0.2                      | minecraft.jar                                        | None                                     |
	| UCH   | advanced-fishing                      | 1.2.0                    | Advanced-Fishing-1.12.2-1.2.0.jar                    | None                                     |
	| UCH   | jei                                   | 4.11.0.212               | jei_1.12.2-4.11.0.212.jar                            | None                                     |
	| UCH   | theoneprobe                           | 1.4.24                   | theoneprobe-1.12-1.4.24.jar                          | None                                     |
	| UCH   | immersiveengineering                  | 0.12-85                  | ImmersiveEngineering-0.12-85.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | alternatingflux                       | 0.12.2-1                 | alternatingflux-0.12.2-1.jar                         | None                                     |
	| UCH   | quark                                 | r1.5-130                 | Quark-r1.5-130.jar                                   | None                                     |
	| UCH   | autoreglib                            | 1.3-20                   | AutoRegLib-1.3-20.jar                                | None                                     |
	| UCH   | basemetals                            | 2.5.0-beta6              | BaseMetals-1.12-2.5.0-beta6.280.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | baseminerals                          | 2.5.0-beta6              | BaseMinerals-1.12-2.5.0-beta6.57.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | bibliotheca                           | 1.3.3-1.12.2             | bibliotheca-1.3.3-1.12.2.jar                         | None                                     |
	| UCH   | biomesoplenty                         | 7.0.1.2398               | BiomesOPlenty-1.12.2-7.0.1.2398-universal.jar        | None                                     |
	| UCH   | carryon                               | 1.10                     | Carry+On+MC1.12.2+v1.10.jar                          | None                                     |
	| UCH   | ctm                                   | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                              | None                                     |
	| UCH   | chisel                                | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| UCH   | cei                                   | 1.3                      | chunkedgeindicator-1.4.jar                           | None                                     |
	| UCH   | redstoneflux                          | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore                              | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar               | None                                     |
	| UCEE  | coherentvillages                      | v1.1.5.0                 | coherent_villages_beta_v1.1.5.jar                    | None                                     |
	| UC    | corail_pillar_extension_biomesoplenty | 4.0.1                    | corail_pillar_extension_biomesoplenty-4.0.1-1.12.jar | None                                     |
	| UC    | corail_pillar_extension_chisel        | 4.0.0                    | corail_pillar_extension_chisel-4.0.0-1.12.jar        | None                                     |
	| UC    | corail_pillar_extension_quark         | 4.0.0                    | corail_pillar_extension_quark-4.0.0-1.12.jar         | None                                     |
	| UC    | crafttweaker                          | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                         | None                                     |
	| UC    | ctgui                                 | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                         | None                                     |
	| UC    | crafttweakerjei                       | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                         | None                                     |
	| UC    | ctdcore                               | 1.4.0                    | CTD-Core-1.12.2-1.4.0.jar                            | b50fe22651b9d97d9d6631514a6a57cd6174b0dc |
	| UC    | cxlibrary                             | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                           | None                                     |
	| UC    | orespawn                              | 3.3.0                    | OreSpawn-1.12-3.3.0.155.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | densemetals                           | 1.2.0                    | DenseMetals-1.12-1.2.0.21.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | drawbridges                           | 0.1                      | Drawbridges-1.0.jar                                  | None                                     |
	| UC    | enderore                              | 1.12.2-v1.1              | Ender+Ore-1.12.2-v1.1.jar                            | None                                     |
	| UC    | endercompass                          | 1.2.6.2                  | EnderCompass-1.12-1.2.6.2.jar                        | None                                     |
	| UC    | modernmetals                          | 2.5.0-beta6              | ModernMetals-1.12-2.5.0-beta6.139.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | endmetals                             | 1.2.0-beta4              | EndMetals-1.12-1.2.0-beta4.53.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | engineersdoors                        | 0.7.2                    | engineersdoors-0.7.2.jar                             | None                                     |
	| UC    | forgelin                              | 1.7.4                    | Forgelin-1.7.4.jar                                   | None                                     |
	| UC    | giacomosfoundry                       | 1.3.13                   | GiacomosFoundry-1.12.2-1.3.13.jar                    | None                                     |
	| UC    | guielevator                           | 2.5-[1.10.2]             | GuiElevator-[1.12.2]-2.5.jar                         | None                                     |
	| UC    | hammercore                            | 2.0.2.3                  | HammerCore-1.12.2-2.0.2.3.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UC    | horsepower                            | 2.6.1                    | HorsePower-1.12.2-2.6.1.68.jar                       | cd7e958342770a8b17c919055da42c24dfefd879 |
	| UC    | immersivepetroleum                    | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
	| UC    | immersivetech                         | 1.3.10                   | immersivetech-1.12-1.3.10.jar                        | None                                     |
	| UC    | inventorytweaks                       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironbackpacks                         | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                    | None                                     |
	| UC    | harvestcraft                          | 1.12.2z                  | Pam's+HarvestCraft+1.12.2z.jar                       | None                                     |
	| UC    | jehc                                  | 1.12.2                   | JEHC-1.12.2-1.6.1.0.jar                              | None                                     |
	| UC    | jeiintegration                        | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                   | None                                     |
	| UC    | journeymap                            | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                          | None                                     |
	| UC    | jeid                                  | 1.0.1-16                 | JustEnoughIDs-1.0.1-16.jar                           | None                                     |
	| UC    | justenoughpetroleum                   | 0.1                      | JustEnoughPetroleum-0.1.jar                          | None                                     |
	| UC    | keyboardkeybinds                      | 1.0                      | keyboardkeybinds-1.1.jar                             | None                                     |
	| UC    | lootbags                              | 2.5.6                    | LootBags-1.12.2-2.5.6.jar                            | None                                     |
	| UC    | lunatriuscore                         | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar          | None                                     |
	| UC    | malisiscore                           | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                         | None                                     |
	| UC    | malisisblocks                         | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                       | None                                     |
	| UC    | malisisdoors                          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
	| UC    | malisisswitches                       | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar                     | None                                     |
	| UC    | moglowstone                           | 1.5.6                    | Mo-Glowstone-1.12.2-1.5.6.jar                        | b50fe22651b9d97d9d6631514a6a57cd6174b0dc |
	| UC    | morefurnaces                          | 1.10.5                   | MoreFurnaces-1.12.2-1.10.5.jar                       | None                                     |
	| UC    | multipagechest                        | 1.9.1                    | MultiPageChest-1.12-1.9.1.jar                        | None                                     |
	| UC    | multiplelights                        | 1.0.2                    | MultipleLights-1.12.x-1.0.2.jar                      | None                                     |
	| UC    | nethermetals                          | 1.2.0-beta4              | NetherMetals-1.12-1.2.0-beta4.65.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | recipehandler                         | 0.11                     | NoMoreRecipeConflict-0.11(1.12.2).jar                | None                                     |
	| UC    | oresalleasy                           | 0.1.0.22                 | OresAllEasy-1.12.2-0.1.0.22.jar                      | None                                     |
	| UC    | powerinventory                        | 2.3.1                    | OverpoweredInventory-1.12-2.3.1.jar                  | None                                     |
	| UC    | ropeladders                           | 2.0.0                    | RopeLadders-1.12.2-2.0.0.jar                         | None                                     |
	| UC    | rustic                                | 1.0.9                    | rustic-1.0.9.jar                                     | None                                     |
	| UC    | rusticbopwoods                        | 1.0                      | rusticbopwoods-1.0.jar                               | None                                     |
	| UC    | schematica                            | 1.8.0.169                | Schematica-1.12.2-1.8.0.169-universal.jar            | None                                     |
	| UC    | sgcraft                               | 1.13.2                   | SGCraft-1.3-mc1.12.2.jar                             | None                                     |
	| UC    | shipwrecks_winslow                    | 2.0.0                    | shipwrecks-mc1.12.2-2.0.0.jar                        | None                                     |
	| UC    | simplequarry                          | 25r                      | SimpleQuarry-1.12.2-25r.jar                          | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UC    | superminer_core                       | 2.6.34.336               | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_captivator                 | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_cropinator                 | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_excavator                  | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_illuminator                | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_lumbinator                 | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_shaftanator                | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_substitutor                | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | superminer_veinator                   | [1.12]-2.6.34.336        | SuperMiner-2.6.34.336.jar                            | None                                     |
	| UC    | tombstone                             | 3.1.2                    | tombstone-3.1.2-1.12.jar                             | None                                     |
	| UC    | underwaterrails                       | 1.0.0                    | underwaterrails-1.0.0-universal.jar                  | None                                     |
	| UC    | uppers                                | 0.0.6                    | Uppers-0.0.6.jar                                     | None                                     |
	| UC    | veinminer                             | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| UC    | veinminermodsupport                   | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                | None                                     |
	| UC    | shetiphiancore                        | 3.5.8                    | shetiphiancore-1.12.0-3.5.8.jar                      | None                                     |
	| UC    | corail_pillar                         | 4.1.0                    | corail_pillar-4.1.0-1.12.jar                         | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
HCASM (HammerCore-1.12.2-2.0.2.3.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
MuonPlugin (muon-0.2-1.12.jar)
  gd.izno.mc.muon.MuonClassTransformer
BaseMetals (BaseMetals-1.12-2.5.0-beta6.280.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
JEIDLoadingPlugin (JustEnoughIDs-1.0.1-16.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8673' Renderer: 'ATI Radeon HD 4600 Series'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 242 names; 446 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Simple Quarry (simplequarry) @25r

	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.8673
	OpenGlRenderer: ATI Radeon HD 4600 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by TheExceptionist** [comment]
Yea, an in game config can take some time
Try deleting your current config file and make sure when you change the values that you don't mess with the spelling of the biome names

**Comment by TheExceptionist** [comment]
The crash is basically saying you messed with one of the biome names

**Comment by TheExceptionist** [comment]
Added error checking so it should work in the next version

**Comment by dave75vgnut** [comment]
Here is part of your config:
mark each biome name with either a 0 or 1 to turn them on/off
#Ex: Ocean=1 turns on the village in the ocean biome
#Ex: Ocean=0 turns off the village in the ocean biome
Ocean=1Plains=1Desert=1
If I changed Ocean=0Plains=1Desert=1 it would crash

**Comment by TheExceptionist** [comment]
Did you update?
And you're not suppose to let the  changes be all on one line
It should be:
Ocean=0
Plains=1
Desert=1

**Comment by TheExceptionist** [comment]
Although it shouldn't be crashing in the newer versions because I added a formatting check

**Comment by TheExceptionist** [comment]
It's just that an in game config is a lot more complicated than it sounds

**Comment by dave75vgnut** [comment]
Thanks for the info. That's the way the config generated for me I'll try putting spaces between the biome on/off and biome name. 
Like this: Ocean=1Plains=1Desert=1 to 
Ocean=0
Plains=1
Desert=1

**Comment by TheExceptionist** [comment]
Yeah, that should work
