### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by agentwolf88** [TheExceptionist/Coherent-Villages#19]
https://paste.dimdev.org/oqipekucop.mccrash

**Comment by TheExceptionist** [comment]
My mistake, been rushing out update for the past couple of days

**Comment by agentwolf88** [comment]
No problem. Keep up the good work!

**Comment by TheExceptionist** [comment]
Should be fixed in the next update

**Comment by agentwolf88** [comment]
Good job!

**Comment by TheExceptionist** [comment]
Fixed?

**Comment by P3rf3ctXZer0** [comment]
Yes
