### ISSUE TITLE
Villages spawning too close together

### ISSUE THREAD

**Issue by Lordbaane** [TheExceptionist/Coherent-Villages#2]
Is there a way, (or an addition) to lower the spawn rate a bit? I had three villages spawn in the water within spitting distance of each other and I stopped before it added anymore.
I like the idea of increasing the spawn rate, but maybe have the option in a config file to alter the rate.

**Comment by TheExceptionist** [comment]
Yea, I was planning on doing that for the next update. Thanks for your feedback.

**Comment by drakray** [comment]
Beat me to it :D
I got at least 4 in rendering distance lol

**Comment by TheExceptionist** [comment]
Added a config file that fixes this
