### ISSUE TITLE
Village generation

### ISSUE THREAD

**Issue by JRLTRS** [TheExceptionist/Coherent-Villages#23]
I'm not exactly sure which is a conflict between mods or normal generation problems. But some bugs that I captured made it look like two villages generated one above other. Some of those might be Forestry and Immersive Engineering problems but others are only bugs related with Coherent Villages

![2018-10-02_14 12 07](https://user-images.githubusercontent.com/43751612/46365216-6770e200-c64e-11e8-921e-8670d85ac7a9.png)
![2018-10-02_14 07 09](https://user-images.githubusercontent.com/43751612/46365217-68097880-c64e-11e8-856c-97cc074f56c0.png)
![2018-10-02_14 07 15](https://user-images.githubusercontent.com/43751612/46365218-68097880-c64e-11e8-8f96-e5023eda996a.png)
![2018-10-02_14 07 27](https://user-images.githubusercontent.com/43751612/46365221-68097880-c64e-11e8-93e3-6274fc6c13b8.png)
![2018-10-02_14 08 03](https://user-images.githubusercontent.com/43751612/46365222-68097880-c64e-11e8-9de2-306bda7965cb.png)
![2018-10-02_14 08 13](https://user-images.githubusercontent.com/43751612/46365224-68a20f00-c64e-11e8-96d2-dbeec48b388a.png)

**Comment by TheExceptionist** [comment]
Yea, the generation is pretty wacky. I'll have to deal with it a bit later once I can work out a better method

**Comment by TheExceptionist** [comment]
Fixed in the newer versions hopefully
