### ISSUE TITLE
villager names

### ISSUE THREAD

**Issue by paradoxmeem** [TheExceptionist/Coherent-Villages#25]
![2018-10-06_04 46 09](https://user-images.githubusercontent.com/42090353/46570526-c66e7980-c922-11e8-8409-02f6025604f9.png)
villager names being null null whenever i talk to them. this happened only to one group of soldiers in one building so far.
(also creepers and such should attack guards and vice versa, whats up with that?)
(also also there should be builders or something incase buildings get ruined/destroyed, or to expand the villages with more building/upgrade buildings)

**Comment by TheExceptionist** [comment]
Yea, I've had that come up a couple of times. I'll see what I can do

**Comment by TheExceptionist** [comment]
Guards attack mobs, but there's nothing I can do to get vanilla mobs to attack them

**Comment by paradoxmeem** [comment]
theres also an issue of modded blocks spawning in veins inside the frames of the villages [2018-10-07_20 43 11](https://user-images.githubusercontent.com/42090353/46590578-a4374180-ca71-11e8-9187-0d71e67896f4.png)

**Comment by TheExceptionist** [comment]
That"s not an issue actually

**Comment by TheExceptionist** [comment]
Happens with regular blocks too

**Comment by CrazyJake88** [comment]
The null null name in chat has come up with every village ive come across.

**Comment by TheExceptionist** [comment]
Are you on a server?

**Comment by paradoxmeem** [comment]
singleplayer

**Comment by TheExceptionist** [comment]
What happens in the newest version?

**Comment by paradoxmeem** [comment]
cant seem to find this issue after gutting an entire village, so i dont think this is happening anymore. this did happen in a group that spawned in a building but that was it, but i couldnt find the issue myself in the new version. anyways, found a new bug that i forgot to mention,
![2018-10-15_00 15 14](https://user-images.githubusercontent.com/42090353/46933126-f4814700-d00f-11e8-897e-850792c2ca53.png)

**Comment by TheExceptionist** [comment]
Yeah, this problem should be solved in the newer version
