### ISSUE TITLE
bandit spawn rates.

### ISSUE THREAD

**Issue by xannor** [TheExceptionist/Coherent-Villages#26]
The bandit mobs are interesting but there does not seem to be a limit or control on their spawning. I set the rate to 1 and my world still gets flooded with bandits taking over all of my caves and spamming the logs with their hilarious demises, and making caving extremely dangerous. I disabled them for the time being, though it was interesting to see them take over the village near my base, and surprising to stumble upon a village of bandits. 

I also noticed another couple of other issues, though I don't know if you want a separate report for them.

1) the villager horses seem to inherit from the undead horse. normally this is not an issue but I have the Monk mod and every-time I look at one of them they get withered.

2) i disabled deep ocean villages but I noticed that antique atlas still thinks there is one in the deep ocean (I didn't see one under the water, now there is an idea, aquatic village.)

**Comment by TheExceptionist** [comment]
Yea, I'm aware of the high bandit spawn rate.
Horses aren't undead in the newer version I believe but I'll check.
 I have a way to fix this though, thanks for the feedback.

**Comment by TheExceptionist** [comment]
Fixed in the newest version
