### ISSUE TITLE
Unable to prevent villages from spawning in the ocean

### ISSUE THREAD

**Issue by capt-slowpoke** [TheExceptionist/Coherent-Villages#28]
Turning the ocean, deepocean, and frozenocean biomes to 0 does not seem to prevent them from spawning in the middle of the ocean. Is there a fix for this?

**Comment by TheExceptionist** [comment]
I'll take a look, thanks for reporting

**Comment by Lordbaane** [comment]
That's the funny thing, if you wanted to do a waterworld, this mod has no issues on generation. But I think maybe it has something to do with the fact that ocean's don't have a lot going on until 1.13. 
One of the other modders has crab gen for water and it becomes a lag issues as there aren't anything else for monsters being generated so it becomes the go to.

**Comment by TheExceptionist** [comment]
My mod doesn't generate in superflat presets

**Comment by TheExceptionist** [comment]
Obsolete issue
