### ISSUE TITLE
Feature Request: Disable raids on specific towns

### ISSUE THREAD

**Issue by CrazyJake88** [TheExceptionist/Coherent-Villages#29]
I'd like to set up a village as part of a server spawn point, but it getting attacked by raids might be troublesome. Could there be a tag or a block placed to disable a raid for that area only?

**Comment by TheExceptionist** [comment]
I'll try

**Comment by TheExceptionist** [comment]
Raid have been temporarily disabled in the new version.
They will return though when I finish the faction Mechanic
