### ISSUE TITLE
[Bug] Generated Bed

### ISSUE THREAD

**Issue by drakray** [TheExceptionist/Coherent-Villages#3]
in the small sloped-roof building
![2018-09-17_20 00 41](https://user-images.githubusercontent.com/4303126/45658659-49d44200-babe-11e8-9169-e8f72ddd3a48.png)
Opening the chest make the bed disappear

**Comment by TheExceptionist** [comment]
Thanks, will fix on tomorrow's update

**Comment by TheExceptionist** [comment]
![2018-09-17_22 11 39](https://user-images.githubusercontent.com/9342315/45662257-ba7f5c80-bac6-11e8-9a09-5936fc8693b2.png)
Fixed!
