### ISSUE TITLE
CV Villagers not respecting villager spawn limits?

### ISSUE THREAD

**Issue by PurpleHel** [TheExceptionist/Coherent-Villages#32]
It seems that the Coherent Villages villagers don't respect villager spawn limits? I'm getting ridiculous numbers of soldiers in my villages. Here, have an x-rayed screenshot of one of the barracks/hotel buildings. https://imgur.com/a/mNFraPB

Edit-They were all merchant guards, for whom there doesn't seem to be a config entry.

**Comment by TheExceptionist** [comment]
Noted, but this shouldn't be a problem in the Pre-release version, that is apparently still under review. Expect it to go through sometime today

**Comment by PurpleHel** [comment]
Cool, will update and see!

**Comment by TheExceptionist** [comment]
New update coming out today
