### ISSUE TITLE
Pre-Release v0.0.1.2 NoSuchMethodError ... isBlocking()

### ISSUE THREAD

**Issue by kreezxil** [TheExceptionist/Coherent-Villages#35]
Dedicated server crashing when a player logs on near a specific village.

https://pastebin.com/YC9jHN20

Appears to be a conflict with Dynamic Trees will cross post there too.

**Comment by kreezxil** [comment]
I edited out the habib mob and now an ant worker is causing issue
https://pastebin.com/KwUpQTxe

**Comment by TheExceptionist** [comment]
Fixed in the newest update. Tell me if problems persist
