### ISSUE TITLE
Do you take suggestions? I have an idea if you're going to add creatures

### ISSUE THREAD

**Issue by Sunconure11** [TheExceptionist/Coherent-Villages#36]
Why not add some creatures relating to each group's culture, as you work on them? Here's an example for the latin culture.

https://en.wikipedia.org/wiki/Lemures

**Comment by TheExceptionist** [comment]
Yea. I'll have to do more research before I can put it in

**Comment by TheExceptionist** [comment]
Added in the next update

**Comment by Sunconure11** [comment]
I'll use this to suggest creatures for various cultures, not sure if they'd make it in or not, but I can list some over time.

Norse:

Valravn (https://en.wikipedia.org/wiki/Valravn)

You might want to look for yourself when implementing such things, though. Also, I think you should post more screenshots and what not to curseforge.
