### ISSUE TITLE
[0.0.2.1] ClassCastException

### ISSUE THREAD

**Issue by kreezxil** [TheExceptionist/Coherent-Villages#37]
A player on my server is having crashing issues apparently something to do with Nords.

Client Crash Report: https://pastebin.com/VKn4B8jP

**Comment by TheExceptionist** [comment]
What version are you running

**Comment by kreezxil** [comment]
0.0.2.1

**Comment by TheExceptionist** [comment]
Update to the newest version

**Comment by TheExceptionist** [comment]
0.0.2.2

**Comment by kreezxil** [comment]
you forgot to update you internal version numbers then, because I'm on it. 

![image](https://user-images.githubusercontent.com/3880072/47456472-422d4a80-d79a-11e8-833b-5bbea009bdc0.png)

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/47456529-68eb8100-d79a-11e8-99eb-cf3d94ab52f9.png)

**Comment by TheExceptionist** [comment]
Yea, I noticed that did you update to the one that says 0.0.2.4?
