### ISSUE TITLE
[Bug] Generated Guard Tower

### ISSUE THREAD

**Issue by drakray** [TheExceptionist/Coherent-Villages#4]
![2018-09-17_20 07 23](https://user-images.githubusercontent.com/4303126/45658669-67a1a700-babe-11e8-930f-1a93fe6b15c0.png)
![2018-09-17_20 07 32](https://user-images.githubusercontent.com/4303126/45658674-6c665b00-babe-11e8-9654-6c326cec09f8.png)

**Comment by TheExceptionist** [comment]
Yeah, I was aware. Might take a while for my to fix.
Thanks Again!

**Comment by TheExceptionist** [comment]
Fixed! Probably the last thing I'll do before I release today's update.
