### ISSUE TITLE
Want to help

### ISSUE THREAD

**Issue by mikestahh** [TheExceptionist/Coherent-Villages#41]
Hey man- I'd love to help with textures and structures. I posted about this on the curseforge page a few days ago, but I'm impatient, so I'm posting here too lol.
Anyway, if you would like my help, you can contact me on Discord at mikestah#5011 or on curse at https://www.curseforge.com/members/CSlay
Good luck with the project,
mikestah

**Comment by TheExceptionist** [comment]
I've DMed you with the details
