### ISSUE TITLE
Village NPCs immediately hostile to the player (Coherent-Villages + Rough Mobs 2)

### ISSUE THREAD

**Issue by Drag0nsaver** [TheExceptionist/Coherent-Villages#46]
An interesting turn of events, the village NPCs will become immediately hostile to the player when [Rough Mobs 2](https://minecraft.curseforge.com/projects/rough-mobs-2) is installed and active. Seems to come up intermittently. At times I was outright attacked at first sight (meaning i've had no interaction with them at all yet), others they'd be passive for a time and then attack me when I was passing the night away inside a building, getting damaged by zombies seemed to enrage them at me.

I've also left a comment on the [Rough Mobs 2 issue tracker](https://minecraft.curseforge.com/projects/rough-mobs-2/issues/27) for this.

**Comment by TheExceptionist** [comment]
Ok, will take a look

**Comment by xinwolfthorn** [comment]
i believe this was a bug in rough mobs 2, because the same thing happened with tamed pets and rough mobs 2. i reported that problem and is now fixed.
