### ISSUE TITLE
[Feature] Spawn Config, lowering rogue villager

### ISSUE THREAD

**Issue by drakray** [TheExceptionist/Coherent-Villages#5]
![2018-09-17_20 16 00](https://user-images.githubusercontent.com/4303126/45658684-7daf6780-babe-11e8-9e1a-99fd7541d060.png)

Got a bunch of your villager spawning outside the village, it started at like 4, and 2 minute after several dozen :/

**Comment by TheExceptionist** [comment]
Yeah, I need to fix that spawn rate too
Thanks, really! A lot of suggestions/features coming from you 👍

**Comment by drakray** [comment]
Yeah, it's a thing I do to change my mind from C# coding lol XD

**Comment by TheExceptionist** [comment]
Nice, C# isn't to different from Java. 
Also I add a config option for the spawn rate
