### ISSUE TITLE
[Bug/BadBehavior] Villager attacking passive follower

### ISSUE THREAD

**Issue by drakray** [TheExceptionist/Coherent-Villages#9]
Namely, Luggage from OpenBlocks.
I'll test with more follower-type entities, like Summon from EBWizardry, Golem from Thaumcraft and Extra Golems.

Villager attack at least Luggage, and sometime shoot each other with arrow(didn't have a look at potion-throwing villager yet)

Maybe a config to black/white-list entity by name, or make it to only attack aggressive mobs?

**Comment by drakray** [comment]
They also attacked Chicken from More/Extra/Chickens, slaughtered them all :S

**Comment by TheExceptionist** [comment]
I'll work on these bugs as soon as I add the last set of village types... The Knight
That way I can just deal with all the bugs in one go

**Comment by TheExceptionist** [comment]
May have found a way to fix this

**Comment by drakray** [comment]
I THINK it's fixed in 1.2.1 though, as a quick test(eggSpawing Hunter and a couple other near Luggage and some Chickens and ExoticBirds) seems to show them cohabiting

**Comment by TheExceptionist** [comment]
Well, I'm for certain that it's fixed now. Added a check to see if the targeted entity is tameable, and not to attack it if it is
